apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-0
spec:
  type: ExternalName
  externalName: redis.redis.svc.cluster.local
  ports:
  - port: 6379
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-1
spec:
  type: ExternalName
  externalName: redis.redis.svc.cluster.local
  ports:
  - port: 6379
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-2
spec:
  type: ExternalName
  externalName: redis.redis.svc.cluster.local
  ports:
  - port: 6379
    protocol: TCP